ProjetJB2/Models/Project.cs
using Foolproof;
using ProjetJB2.Controllers;
using System;
using System.ComponentModel;

namespace ProjetJB2.Models
{
    public class Project
    {
        public int Id { get; set; }
        [DisplayName("Title")]
        public String Name { get; set; }
        public String Description { get; set; }
        [DisplayName("Teacher")]
        public Nullable<int> TeacherId { get; set; }
        public virtual Teacher Teacher { get; set; }
        [DisplayName("Starting date")]
        public DateTime BeginDate { get; set; }
        [DisplayName("Ending date")]
        // Classe à parfaire 
        [GreaterThan("BeginDate")]
        public DateTime EndDate { get; set; }
    }
}

ProjetJB2/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetJB2.Models;

namespace ProjetJB2.Controllers
{
    public class ProjectController : Controller
    {
        private ProjetJB2Context db = new ProjetJB2Context();

        public ViewResult Index(String searchString)
        {
            var projects = from p in db.Projects
                           select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                projects = projects.Where(p => p.Name.Contains(searchString) || p.Description.Contains(searchString));
            }
            return View(projects.ToList());
        }
        // GET: Project/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            //GERER LES DATES PASSEES
            var task = db.Tasks.Where(x => x.Project.Id == id && x.EndDate > DateTime.Now).OrderBy(x => x.EndDate).FirstOrDefault();            
            var step = db.Steps.Where(x => x.Project.Id == id && x.EndDate > DateTime.Now).OrderBy(x => x.EndDate).FirstOrDefault();
            var students = new List<Student>();
            var group = db.Groups.Where(x => x.NumGroup == id).ToList();
            foreach(var g in group)
            {
                var studentList = db.Students.Where(x => x.Id == g.StudentId).ToList();
                foreach(var student in studentList)
                {
                    students.Add(student);
                }
                
            }
                
            ProjectStepTaskStudentGroup projectsteptaskstudentgroup = new ProjectStepTaskStudentGroup(project, step, task, students, group);
            return View(projectsteptaskstudentgroup);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "LastName");
            return View();
        }

        // POST: Project/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,TeacherId,BeginDate,EndDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "LastName", project.TeacherId);
            return View(project);
        }

        // GET: Project/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "LastName", project.TeacherId);
            return View(project);
        }

        // POST: Project/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,TeacherId,BeginDate,EndDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "LastName", project.TeacherId);
            return View(project);
        }

        // GET: Project/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Project project = await db.Projects.FindAsync(id);
            foreach (var group in db.Groups.Where(g => g.ProjectId == id))
            {
                db.Groups.Remove(group);
            }
            foreach (var step in db.Steps.Where(s => s.ProjectId == id))
            {
                db.Steps.Remove(step);
            }
            foreach (var task in db.Tasks.Where(t => t.ProjectId == id))
            {
                db.Tasks.Remove(task);
            }
            db.SaveChanges();
            db.Projects.Remove(project);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetJB2/Controllers/StepController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetJB2.Models;

namespace ProjetJB2.Controllers
{
    public class StepController : Controller
    {
        private ProjetJB2Context db = new ProjetJB2Context();

        // GET: Steps
        public ActionResult Index()
        {
            var steps = db.Steps.Include(s => s.Project);
            return View(steps.ToList());
        }

        public ActionResult IndexBis(int id)
        {
            var steps = db.Steps.Where(s=> s.ProjectId == id).Include(s => s.Project);
            return View(steps.ToList());
        }

        // GET: Steps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Step step = db.Steps.Find(id);
            if (step == null)
            {
                return HttpNotFound();
            }
            return View(step);
        }

        // GET: Steps/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            return View();
        }

        // POST: Steps/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,BeginDate,EndDate,ProjectId")] Step step)
        {
            if (ModelState.IsValid)
            {
                db.Steps.Add(step);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", step.ProjectId);
            return View(step);
        }

        // GET: Steps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Step step = db.Steps.Find(id);
            if (step == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", step.ProjectId);
            return View(step);
        }

        // POST: Steps/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,BeginDate,EndDate,ProjectId")] Step step)
        {
            if (ModelState.IsValid)
            {
                db.Entry(step).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", step.ProjectId);
            return View(step);
        }

        // GET: Steps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Step step = db.Steps.Find(id);
            if (step == null)
            {
                return HttpNotFound();
            }
            return View(step);
        }

        // POST: Steps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Step step = db.Steps.Find(id);
            db.Steps.Remove(step);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        /*Upload des Fichiers*/
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            //Sauvegarde du Fichier dans le dossier Files
            file.SaveAs("C:\\Users\\yis75\\source\\repos\\ProjetJB2---Restart\\ProjetJB2\\Files\\" + file.FileName);

            //db.Files.Add(file);

            return RedirectToAction("Index");
        }

        /*Download des Fichiers*/
        [HttpPost]
        public ActionResult DownloadFile(int? fileId)
        {

            return RedirectToAction("Index");
        }
    }
}

ProjetJB2/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetJB2.Models;

namespace ProjetJB2.Controllers
{
    public class TaskController : Controller
    {
        private ProjetJB2Context db = new ProjetJB2Context();

        // GET: Task
        public async Task<ActionResult> Index()
        {
            var tasks = db.Tasks.Include(t => t.Project).Include(t => t.Student);
            return View(await tasks.ToListAsync());
        }

        public ActionResult IndexBis(int id)
        {
            var tasks = db.Tasks.Where(t => t.ProjectId == id).Include(t => t.Project);
            return View(tasks.ToList());
        }

        // GET: Task/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Task task = await db.Tasks.FindAsync(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Task/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            ViewBag.StudentId = new SelectList(db.Students, "Id", "LastName");
            return View();
        }

        // POST: Task/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Description,BeginDate,EndDate,State,ProjectId,StudentId")] Models.Task task)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", task.ProjectId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "LastName", task.StudentId);
            return View(task);
        }

        // GET: Task/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Task task = await db.Tasks.FindAsync(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", task.ProjectId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "LastName", task.StudentId);
            return View(task);
        }

        // POST: Task/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Description,BeginDate,EndDate,State,ProjectId,StudentId")] Models.Task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", task.ProjectId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "LastName", task.StudentId);
            return View(task);
        }

        // GET: Task/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Task task = await db.Tasks.FindAsync(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Models.Task task = await db.Tasks.FindAsync(id);
            db.Tasks.Remove(task);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetJB2/Views/Project/Create.cshtml
@model ProjetJB2.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "Index", new { id = "backList" }, new { @class = "btn btn-danger" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetJB2/Views/Project/Delete.cshtml
@model ProjetJB2.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Teacher.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index", new { id = "backList" }, new { @class = "btn btn-danger" })
    </div>
    }
</div>

ProjetJB2/Views/Project/Details.cshtml
@model ProjetJB2.Models.ProjectStepTaskStudentGroup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project : @Html.DisplayFor(model => model.Project.Name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.Teacher.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Teacher.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt>
            Students
        </dt>
        
            @foreach (var item in Model.Students)
        {
        <dd>
            @Html.DisplayFor(modelItem => item.LastName)  @Html.DisplayFor(modelItem => item.FirstName)
        </dd>
            }
        
        <dt>
            @Html.DisplayNameFor(model => model.Project.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.EndDate)
        </dd>

        <dt>
            Next Step
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Step.Description) - (Date) : @Html.DisplayFor(model => model.Step.EndDate)
        </dd>
        <dt>
            Next Task
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task.Description) - (Date) : @Html.DisplayFor(model => model.Task.EndDate)
        </dd>

        <dt>
            @Html.ActionLink("Steps detail", "IndexBis", "Step", new { id = Model.Project.Id }, null)
        </dt>

        <dd></dd>

        <dt>
            @Html.ActionLink("Tasks detail", "IndexBis", "Task", new { id = Model.Project.Id }, null)
        </dt>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Project.Id }) |
    @Html.ActionLink("Back to List", "Index", new { id = "backList" }, new { @class = "btn btn-danger" })
</p>

ProjetJB2/Views/Project/Edit.cshtml
@model ProjetJB2.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit project</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "Index", new { id = "backList" }, new { @class = "btn btn-danger" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetJB2/Views/Project/Index.cshtml
@model IEnumerable<ProjetJB2.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h1 class="page-header">Projects List</h1>

<p>
    @Html.ActionLink("New Project", "Create", new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Teacher.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <!-- faute de mieux -->
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Teacher.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
        </td>
        
    </tr>
    }

</table>